#include "creeper_sim/mujoco_backend.h"
#include "creeper_sim/joint_mapping.h"
#include <mujoco/mujoco.h>
#include <algorithm>
#include <cmath>
namespace creeper_sim {
namespace {int sensorId(const mjModel*m,const char*n){return mj_name2id(m,mjOBJ_SENSOR,n);} const mjtNum* sensor(const mjModel*m,const mjData*d,int id){return id<0?nullptr:d->sensordata+m->sensor_adr[id];}}
MujocoBackend::MujocoBackend()=default; MujocoBackend::~MujocoBackend(){if(data_)mj_deleteData(data_);if(model_)mj_deleteModel(model_);}
bool MujocoBackend::load(const std::string&p,std::string&e){char buf[1024]{};model_=mj_loadXML(p.c_str(),nullptr,buf,sizeof(buf));if(!model_){e=buf;return false;}data_=mj_makeData(model_);if(!data_){e="mj_makeData failed";return false;}base_body_id_=mj_name2id(model_,mjOBJ_BODY,"base");if(base_body_id_<0){e="missing base body";return false;}
 for(int i=0;i<12;++i){joint_id_[i]=mj_name2id(model_,mjOBJ_JOINT,kJointNames[i].data());actuator_id_[i]=mj_name2id(model_,mjOBJ_ACTUATOR,kActuatorNames[i].data());std::string base(kJointNames[i]);base.resize(base.size()-6);joint_pos_sensor_[i]=sensorId(model_,(base+"pos").c_str());joint_vel_sensor_[i]=sensorId(model_,(base+"vel").c_str());force_sensor_[i]=sensorId(model_,(base+"force").c_str());if(joint_id_[i]<0||actuator_id_[i]<0||joint_pos_sensor_[i]<0||joint_vel_sensor_[i]<0||force_sensor_[i]<0){e="missing joint/actuator/sensor "+std::string(kJointNames[i]);return false;}qpos_adr_[i]=model_->jnt_qposadr[joint_id_[i]];dof_adr_[i]=model_->jnt_dofadr[joint_id_[i]];lower_[i]=model_->jnt_range[2*joint_id_[i]];upper_[i]=model_->jnt_range[2*joint_id_[i]+1];}
 const char*feet[]={"FL_foot_touch","FR_foot_touch","RL_foot_touch","RR_foot_touch"};for(int i=0;i<4;++i)if((foot_touch_sensor_[i]=sensorId(model_,feet[i]))<0){e="missing foot touch sensor";return false;}imu_quat_=sensorId(model_,"imu_quat");imu_gyro_=sensorId(model_,"imu_gyro");imu_accel_=sensorId(model_,"imu_accel");if(imu_quat_<0||imu_gyro_<0||imu_accel_<0){e="missing IMU sensor";return false;}return true;}
bool MujocoBackend::reset(const std::string&key,std::string&e){if(!data_){e="not loaded";return false;}mj_resetData(model_,data_);int id=mj_name2id(model_,mjOBJ_KEY,key.c_str());if(id<0){e="unknown keyframe: "+key;return false;}mj_resetDataKeyframe(model_,data_,id);mj_forward(model_,data_);estimated_world_velocity_.fill(0);estimator_time_=data_->time;return true;}
RobotState MujocoBackend::readState(StateMode mode)const{RobotState s;if(!data_)return s;s.time=data_->time;s.base_height=data_->qpos[2];for(int i=0;i<12;++i){if(mode==StateMode::SensorEmulation){s.joint_position[i]=sensor(model_,data_,joint_pos_sensor_[i])[0];s.joint_velocity[i]=sensor(model_,data_,joint_vel_sensor_[i])[0];s.joint_torque[i]=sensor(model_,data_,force_sensor_[i])[0];}else{s.joint_position[i]=data_->qpos[qpos_adr_[i]];s.joint_velocity[i]=data_->qvel[dof_adr_[i]];s.joint_torque[i]=data_->actuator_force[actuator_id_[i]];}}for(int i=0;i<4;++i)s.contact[i]=sensor(model_,data_,foot_touch_sensor_[i])[0]>.1;
 const mjtNum*q=(mode==StateMode::SensorEmulation?sensor(model_,data_,imu_quat_):data_->qpos+3);for(int i=0;i<4;++i)s.orientation[i]=q[i];mjtNum inv[4],g[3]={0,0,-1},gb[3];mju_negQuat(inv,q);mju_rotVecQuat(gb,g,inv);for(int i=0;i<3;++i)s.projected_gravity[i]=gb[i];
 if(mode==StateMode::SensorEmulation){const mjtNum*w=sensor(model_,data_,imu_gyro_),*a=sensor(model_,data_,imu_accel_);for(int i=0;i<3;++i){s.body_angular_velocity[i]=w[i];s.specific_force[i]=a[i];}double dt=data_->time-estimator_time_;if(dt>0&&dt<.1){mjtNum aw[3];mju_rotVecQuat(aw,a,q);aw[2]-=9.80665;for(int i=0;i<3;++i)estimated_world_velocity_[i]+=dt*aw[i];if(std::any_of(s.contact.begin(),s.contact.end(),[](bool x){return x;}))for(double&v:estimated_world_velocity_)v*=.98;}estimator_time_=data_->time;mjtNum invq[4],vb[3];mju_negQuat(invq,q);mju_rotVecQuat(vb,estimated_world_velocity_.data(),invq);for(int i=0;i<3;++i)s.body_linear_velocity[i]=vb[i];}
 else{mjtNum velocity[6];mj_objectVelocity(model_,data_,mjOBJ_BODY,base_body_id_,velocity,1);for(int i=0;i<3;++i){s.body_angular_velocity[i]=velocity[i];s.body_linear_velocity[i]=velocity[3+i];}}
 s.valid=true;return s;}
void MujocoBackend::applyTorques(const std::array<double,12>&t){for(int i=0;i<12;++i)data_->ctrl[actuator_id_[i]]=t[i];}
void MujocoBackend::step(){mj_step(model_,data_);}double MujocoBackend::timestep()const{return model_?model_->opt.timestep:0;}double MujocoBackend::time()const{return data_?data_->time:0;}
bool MujocoBackend::baseContact()const{if(!data_)return false;int base=mj_name2id(model_,mjOBJ_BODY,"base");for(int i=0;i<data_->ncon;++i){const auto&c=data_->contact[i];int b1=model_->geom_bodyid[c.geom1],b2=model_->geom_bodyid[c.geom2];if(b1==base||b2==base)return true;}return false;}
}
